version: 2
jobs:
  test:
    machine:
      image: circleci/classic:201808-01
    # docker:
    #   - image: cmdlabs/terraform-utils:2.0.0
    
    steps:
      - checkout

      - run:
          name: Init
          command: make init

      - run:
          name: Validate
          command: make validate

      - run:
          name: Format Check
          command: make formatCheck

workflows:
  version: 2
  test:
    jobs:
      - test