version: 2
jobs:
  test:
    docker:
      - image: cmdlabs/terraform-utils:2.0.0

    working_directory: examples
    
    steps:
      - checkout

      - run:
          name: Init
          command: terraform init

      - run:
          name: Validate
          command: terraform validate

      - run:
          name: Format Check
          command: terraform fmt -check ../

workflows:
  version: 2
  test:
    jobs:
      - test