version: 2
jobs:
  test:
    docker:
      - image: cmdlabs/terraform-utils:2.0.0

    steps:
      - checkout

      - run:
          name: Validate
          command: terraform validate examples

      - run:
          name: Format Check
          command: terraform fmt -check .